# Generated by Django 4.2.20 on 2025-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_income_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name=' Время'),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name=' Время'),
        ),
    ]
